### ISSUE TITLE
 Definir o material da viga a partir de cálculos de deformação

### ISSUE THREAD

**Issue by rogerioo** [fga-projeto-integrador-1/Projeto#10]
Utilizar de conceitos de deflexão para se obter um material com a flexibilidade desejada para a viga

**Comment by DaniloFernandesDuarte** [comment]
Foram realizados cálculos para tentar dimensionar uma viga com as propriedades desejadas, mas estamos tendo dificuldades em encontrar uma geometria que nos permita faze-la de madeira compensada

**Comment by rogerioo** [comment]
[Cálculos](https://drive.google.com/drive/folders/1t7Nn0MCSZ9OOt4zIf_tFjoIFK1_NyxW-?usp=sharing) feitos e disponibilizados no drive.
