### ISSUE TITLE
 Criar um orçamento

### ISSUE THREAD

**Issue by rogerioo** [fga-projeto-integrador-1/Projeto#11]
Criar um orçamento para os gastos associados a parte estrutural do projeto, com base no design

**Comment by DaniloFernandesDuarte** [comment]
Temos valores para os gastos com madeira, e vamos iniciar o processo de estimar os gastos que serão tidos com ferragens e outros materiais que serão usados em menor quantidade

**Comment by rogerioo** [comment]
Primeira versão do [documento](https://docs.google.com/spreadsheets/d/1OcmnvuhmSApRgUQ7-J_m2wesk4NHRX1-oH2XPaWJTDw/edit?usp=sharing) disponível no drive.

**Comment by rogerioo** [comment]
Por certas dificuldades encontradas pelo grupo e por ser uma fase essêncial do projeto, essa tarefa foi alocada para a sprint 03 e está sendo atendida por essa [issue](#36).
