### ISSUE TITLE
Concluir design da bancada

### ISSUE THREAD

**Issue by rogerioo** [fga-projeto-integrador-1/Projeto#12]
Definir o design da estrutura da bancada e outros componentes da estrutura

**Comment by DaniloFernandesDuarte** [comment]
A maior parte do design foi concluída com ajustes pequenos dependendo das dimensões finais da viga e propriedades da câmera ainda pendentes.

**Comment by rogerioo** [comment]
[Documentação](https://drive.google.com/file/d/11nO1g9g3CNbI87jucLl2SQ3Bi834nrGj/view?usp=sharing) concluída e disponibilizada no drive.
