### ISSUE TITLE
Documentação da aquisição de materiais

### ISSUE THREAD

**Issue by rogerioo** [fga-projeto-integrador-1/Projeto#13]

**Comment by DaniloFernandesDuarte** [comment]
A documentação será concluída no curso desse final de semana (11/05 e 12/05)

**Comment by rogerioo** [comment]
[Relatório](https://docs.google.com/document/d/1cPVgEc7IoHcLtvr1N_6HctvWDm01TCPp1qfJa6_iQfk/edit?usp=sharing) disponível no drive.
