### ISSUE TITLE
Simulação dos componentes definidos

### ISSUE THREAD

**Issue by rogerioo** [fga-projeto-integrador-1/Projeto#15]
## Descrição da Issue
Fazer simulação do circuito da câmera, usando Proteus ou Fritzing.

### Tasks:
- [x] Fazer o esquemático
- [x] Fazer Relatório de Atividade

### Critérios de aceitação:
- [x] Esquemático.
- [x] Documentação do Esquemático.

## Assignees
@Vkaio 
@iaraandrade

**Comment by iaraandrade** [comment]
Ainda estou estudando/pesquisando como é a comunicação entre a ide da esp32 com o proteus, acredito que tenha achado algo relativamente pronto (pelo menos o início), mas ainda não testei (https://www.dobitaobyte.com.br/primeiros-passos-com-esp32/)

**Comment by matheusgvieira** [comment]
### Andamento da Atividade
O @Vkaio, está desenvolvendo a conexão com a **API**, o servidor ,**Postgresql** (https://www.postgresql.org/), em **WSGI**. Está com dificuldades, mas estão sendo superadas.

**Comment by matheusgvieira** [comment]
### Atualização da Atividade
Durante a reunião hoje às 10 hrs por hangout, tiramos muitas dúvidas sobre a conexão com servidor. Estamos priorizando essa atividade, pois ela é importante para a definição do orçamento.

**Comment by Vkaio** [comment]
Fiz um simulação com o NodeMCU ESP8266, versão anterior da ESP32, apenas para teste de comunicação. Tal simulação foi feita no Proteus

**Comment by matheusgvieira** [comment]
### Atualização da Atividade

Já estamos finalizando, estamos por alguns detalhes, ao longo do dia a atividade estará finalizada.

**Comment by matheusgvieira** [comment]
### ESQUEMÁTICO DO CIRCUITO
![DIVISOR_TENSAO](https://user-images.githubusercontent.com/47388740/57994745-00952180-7a95-11e9-8ad4-e197fb6a59ec.png)
![ESQUEMATICO](https://user-images.githubusercontent.com/47388740/57994747-012db800-7a95-11e9-90f6-9c9070b6e4de.png)

**Comment by rogerioo** [comment]
@matheusgvieira Falta só o relatório da atividade! Mas, ficou muito bom o esquemático.

**Comment by matheusgvieira** [comment]
### Teste com ESP32
[teste_esp32.pdf](https://github.com/ssol-organization/Wiki/files/3196222/teste_esp32.pdf)

**Comment by matheusgvieira** [comment]
### Relatório de Atividade
[Relatório de Atividade - Camera.pdf](https://github.com/ssol-organization/Wiki/files/3196230/Relatorio.de.Atividade.-.Camera.pdf)

**Comment by rogerioo** [comment]
Ficou excelente o relatório. Deu pra entender o passo a passo e ficou muito bem o relatório. Obrigado!
