### ISSUE TITLE
Fechar orçamento dos componentes eletrônicos

### ISSUE THREAD

**Issue by rogerioo** [fga-projeto-integrador-1/Projeto#17]
## Descrição da Issue
Fazer planilha de componentes, orçar total de gasto.

### Tasks:
- [x] Fazer o planilha
- [x] Fazer Relatório de Atividade

### Critérios de aceitação:
- [x] Planilha de Componentes

## Assignees
@haackmarcella  
@iaraandrade

**Comment by matheusgvieira** [comment]
### Atualização da Atividade
A planilha já está sendo realizada.

**Comment by matheusgvieira** [comment]
## Relatório e Planilha

[planilha_componentes.pdf](https://github.com/ssol-organization/Wiki/files/3196241/planilha_componentes.pdf)

**Comment by rogerioo** [comment]
Excelente!
