### ISSUE TITLE
Elicitar os requisitos do Projeto

### ISSUE THREAD

**Issue by rogerioo** [fga-projeto-integrador-1/Projeto#2]
# Issue Template

## Descrição da Issue
Elicitar, modelar e analisar os requisitos que a serem atendidos para o desenvolvimento do protótipo final.

### Tasks:
- [ ] Levantar os requisitos necessários ao protótipo
- [ ] Encontrar um modelo de documento à ser seguido
- [ ] Confeccionar o artefato

## Assignees
@GabrielDVpereira 
@LucasGlopes 
@amandahenriques 
@haackmarcella

**Comment by amandahenriques** [comment]
De início, na pasta do Drive Ponto de Controle 1 > Requisitos, inseri o que seriam os requisitos e exemplos iniciais de como documentar requisitos.

**Comment by rogerioo** [comment]
Excelente @amandahenriques ! 
@GabrielDVpereira passa pra eles alguns pontos que sejam relevantes e que possam usar no contexto e no timebox do projeto.

**Comment by amandahenriques** [comment]
Eu e a Marcella marcamos uma reunião com o Sergio na terça, que se mostrou muito interessado no projeto,  para recolhermos mais dados de requisitos (análise de protocolo). Pretendemos procurar a Suzana e a Glauceny também.

**Comment by rogerioo** [comment]
@amandahenriques Vocês vão criar uma primeira versão do documento até o final da sprint?

**Comment by rogerioo** [comment]
Issue atendida pelo [documento](https://drive.google.com/open?id=1jqauqhYCoeA4TehHNRD49vpWm_9TSDj3) disponível no drive.
