### ISSUE TITLE
Definir tecnologias de programação

### ISSUE THREAD

**Issue by rogerioo** [fga-projeto-integrador-1/Projeto#21]
Definir as técnologias (como linguagens, frameworks ou plataformas) que serão utilizadas para programar cada sistema envolvido no projeto. 

### Critérios de aceitação

- [x]  Definir as técnologias
- [x]  Documentar as definições, com justificativas para as decisões tomadas

**Comment by MarcosNBJ** [comment]
Versão inicial do documento incluindo as definições de tecnologias requisitadas pela issue inclusa no PR #47 .
