### ISSUE TITLE
Definir arquitetura do sistema

### ISSUE THREAD

**Issue by rogerioo** [fga-projeto-integrador-1/Projeto#22]
Definir como será a arquitetura do sistema.

### Critérios de aceitação.

- [x]  Definir como será a arquitetura.
- [x]  Documentar as definições, com justificativas para as decisões tomadas e um diagrama que represente o funcionamento da arquitetura do sistema.

**Comment by MarcosNBJ** [comment]
Versão inicial do documento incluindo as definições de arquitetura pedidas pela issue inclusa no PR #48 .

**Comment by rogerioo** [comment]
Issue concluída com o PR #48 disponível na master.
