### ISSUE TITLE
Definir técnicas de visão computacional

### ISSUE THREAD

**Issue by rogerioo** [fga-projeto-integrador-1/Projeto#24]
Definir quais serão as técnicas de visão computacional utilizadas no projeto.

### Críterios de aceitação

- [x]  Definir as técnicas
- [x]  Documentar as definições, com justificativas para as decisões tomadas.

**Comment by pedroeagle** [comment]
## Teste das técnicas de visão computacional que serão utilizadas no nosso projeto
Acabei de adicionar um teste de técnicas que serão utilizadas no nosso projeto. No momento fiz até a parte de identificação de cores na viga. Está tudo passo a passo em um Jupyter Notebook. Para usar siga o passo a passo:
Entre no diretório docs/tecnicas_visao e dê o seguinte comando para ativar o ambiente virtual
```
source visao/bin/activate
```
Logo depois inicie o Jupyter Notebook com o seguinte comando:
```
jupyter-notebook
```
Abra então o notebook "tecnicas_visao.ipynb"

**Comment by rogerioo** [comment]
A pasta de técnicas foi movida para a pasta raiz do projeto por conta da WIki e o documento está disponível na master.
