### ISSUE TITLE
Definir o escopo do Projeto

### ISSUE THREAD

**Issue by rogerioo** [fga-projeto-integrador-1/Projeto#3]
# Issue Template

## Descrição da Issue
Para guiar o bom desenvolvimento do projeto é necessário definir o conjunto de características que descrevem o resultado final do projeto (o produto acabado).

### Tasks:
- [x] Encontrar modelo de documento a ser seguido
- [x] Definir o escopo do projeto
- [x] Confeccionar o artefato

## Assignees
@jaosvgarcia 
@iaraandrade

**Comment by iaraandrade** [comment]
[tap .docx](https://github.com/fga-projeto-integrador-1/Projeto/files/3103601/tap.docx)

**Comment by rogerioo** [comment]
Documento disponível no drive e primeira versão entregue.
