### ISSUE TITLE
Finalizar o esquema em CAD de toda a bancada

### ISSUE THREAD

**Issue by rogerioo** [fga-projeto-integrador-1/Projeto#32]
## Finalizar o esquema em CAD de toda a bancada e obter imagens para serem usadas na ilustração do projeto no próximo ponto de controle.

- CADs disponíveis em: https://drive.google.com/drive/folders/1cdNKlFeGV4dOlHVyEJKRLkrRkVxEQyo2?usp=sharing

### Critérios de aceitação:

- [x] Definir as dimensões de todos os componentes da bancada;
- [x] Definir quais os materiais serão usados
- [x] Incluir os dados pertinentes a bancada na folha de orçamento;
- [x] Obter screenshots do CAD finalizado

**Comment by DaniloFernandesDuarte** [comment]
Criei uma versão parametrizada do cad da bancada, o que significa que não haverá retrabalho em caso de redimensionamentos dos componentes.

**Comment by DaniloFernandesDuarte** [comment]
Sugeri alternativas de design ao grupo, Esperando confirmação do pessoal de software da viabilidade destas.

**Comment by rogerioo** [comment]
@DaniloFernandesDuarte Você pode colocar o CAD que foi definido aqui pra finalizarmos a issue?

**Comment by DaniloFernandesDuarte** [comment]
Eu posso upar o arquivo, mas para usar a função de knowledge do Catia precisa configurar umas coisas (e a viga acabou não mudando de dimensão então o modelo que já está lá ainda é valido).

Vou deixar umas com as imagens para uso em relatórios:
https://drive.google.com/drive/u/0/folders/1cdNKlFeGV4dOlHVyEJKRLkrRkVxEQyo2
