### ISSUE TITLE
Finalizar os dimensionamento da viga

### ISSUE THREAD

**Issue by rogerioo** [fga-projeto-integrador-1/Projeto#33]
## Encontrar uma solução final para o problema de dimensionamento da viga

(Cálculos disponíveis em:
 https://docs.google.com/spreadsheets/d/16MdHGEufKPm99tJczEV1tLqlbVWdI2Rc8nQqf3qWxlI/edit?usp=sharing )

### Critérios de aceitação:

- [x]  Dimensionar uma viga viável.
- [x] Atentar-se a possíveis mudanças de material (estes também necessitarão cálculos próprios). 
- [x] Conferir se a espessura é suficiente para o processamento de imagem

**Comment by LucasGlopes** [comment]
O @matalencar e eu nos reunimos hoje com o intuito de finalizar o dimensionamento da viga, chegando a algumas conclusões:
 Caso o material escolhido seja mesmo o MDF, já será possível fechar o orçamento da viga. E com base nos dados presentes [nesse documento](http://covema.pt/getattachment/Produtos/Derivados/MDF-Cru-Normal/FICHA_TECNICA_VALBOPAN.pdf) e na [tabela](https://docs.google.com/spreadsheets/d/16MdHGEufKPm99tJczEV1tLqlbVWdI2Rc8nQqf3qWxlI/edit#gid=1986115276) presente no Drive, chegamos às seguintes dimensões que melhor nos atendem:
  Comprimento = 1 metro;
  Largura = 10 centímetros;
  Espessura = 9 milímetros;
  Massa total dos corpos de prova = Aproximadamente 8,3 kg.
 Sobre o acrílico, as pesquisas iniciais mostraram preços altos e valores divergentes do módulo de elasticidade, impossibilitando o término dos cálculos com esse material. Seguiremos pesquisando.

**Comment by rogerioo** [comment]
Guys, vocês podem relatar isso naquele documento de realização de tarefa pfvr? @matalencar e @LucasGlopes

**Comment by matalencar** [comment]
Os cálculos foram realizados e algumas opções para uma viga viável foram encontradas, basta agora decidirmos qual que seria a melhor. Também chegou-se à conclusão de que a espessura da viga não irá atrapalhar no processamento de imagens.

**Comment by matalencar** [comment]
Os resultados encontram-se nesse [relatório](https://docs.google.com/document/d/1f5RZ6l0l-fDEv7ESr9hTBEQwBPrizxeULJcKO4kP1AM/edit)

**Comment by rogerioo** [comment]
Tudo certinho. Obrigado!
