### ISSUE TITLE
Documentação de estruturas da sprint 03

### ISSUE THREAD

**Issue by rogerioo** [fga-projeto-integrador-1/Projeto#35]
### Critérios de aceitação (o documento deve conter):

- [x] Elaboração dos cálculos que foram realizados para o dimensionamento da viga;
- [x] Explicação do processo lógico para a decisão das dimensões da viga, dos pesos;
- [x] Apontar os desafios encontrados nesse processo e como eles foram superados;
- [x] Explicação do processo lógico para a concepção do design da bancada e seus componentes;
- [ ] explicação do processo lógico do design dos apoios e pesos;
- [x] Apontar os desafios encontrados nesse processo e como eles foram superados;

**Comment by DaniloFernandesDuarte** [comment]
Arquivo contendo mais detalhes acerca do design da estrutura disponível em:

https://docs.google.com/document/d/1bDApdqpt7nhahtUsGQfgFFQdYFEz-SDHkNln2RbRHPk/edit?usp=sharing

**Comment by rogerioo** [comment]
@DaniloFernandesDuarte esse relatório faz parte da issue #32 . Se puder colocar lá o atualizado!

**Comment by rogerioo** [comment]
Documento disponível [aqui](https://docs.google.com/document/d/1cPVgEc7IoHcLtvr1N_6HctvWDm01TCPp1qfJa6_iQfk/edit?usp=sharing).
