### ISSUE TITLE
Relatório das atividades realizadas

### ISSUE THREAD

**Issue by rogerioo** [fga-projeto-integrador-1/Projeto#41]
## Descrição da Issue
Criar um documento relatando o cumprido nas issues #42 #38 #39 #54

**Comment by rogerioo** [comment]
@MarcosNBJ como vai ficar essa ultima issue?

**Comment by MarcosNBJ** [comment]
> @MarcosNBJ como vai ficar essa ultima issue?

Creio que idealmente por conta dos relatórios gerados individualmente com o cumprimento de cada issue. Já que um documento único relatando o progresso parcial de criação de código em cada aplicação não faz tanto sentido.

**Comment by rogerioo** [comment]
Isso é verdade! O trabalho já está todo disponível nos repositórios de forma organizada. Essa issue fará sentido quando houver que atualizar na documentação arquitetural.
