### ISSUE TITLE
Definir pontos restantes de visão de produto inicial para o aplicativo

### ISSUE THREAD

**Issue by MarcosNBJ** [fga-projeto-integrador-1/Projeto#44]
Definir, para o aplicativo mobile que será feito, os pontos restantes acerca da visão de produto. Sendo estas o guia de estilo e um protótipo inicial das telas.

### Critérios de aceitação:
- [x] Documento do guia de estilos.
- [x] Protótipo de baixa fidelidade.

**Comment by DanilloGS** [comment]
Fiz uma pesquisa sobre como poderia ser o layout do nosso app, acabei encontrando este formato que achei bacana e poderia servir de inspiração:

![mathrob-2](https://user-images.githubusercontent.com/31555287/57416268-e4ac9880-71d5-11e9-978e-c74e65cedfad.gif)

**Comment by amandahenriques** [comment]
Muito bom pra usar de exemplo!

**Comment by DanilloGS** [comment]
Nosso protótipo de baixa fidelidade esta pronto, segue o link: https://marvelapp.com/5107fie
