### ISSUE TITLE
Definir o planejamento do Projeto

### ISSUE THREAD

**Issue by rogerioo** [fga-projeto-integrador-1/Projeto#5]
# Issue Template

## Descrição da Issue
Definir os materiais necessários e demais coisas para o desenvolvimento do projeto.

### Tasks:
- [x] Pesquisar o que é necessário para o planejamento à ser entregue no Ponto de Controle I
- [x] Encontrar modelo de documento à ser seguido
- [x] Definir o planejamento
- [x] Confeccionar artefato

## Assignees
@matheusgvieira 
@joao15victor08

**Comment by matheusgvieira** [comment]
# Planejamento

<p align = "justify">Nas fases de projeto, o momento do planejamento é de suma importância, e pode determinar todo o sucesso daquele projeto.  Realizada uma revisão do orçamento do projeto, é criada a EAP (Estrutura Analítica do Projeto) ou WBS (Work Breakdown Structure), detalha-se o escopo do projeto e as atividades que serão necessárias.</p>

<p align = "justify">Nesta hora também acontece o refinamento dos objetivos, com sequenciamento de atividades, negociações de apoio a patrocínio. Neste momento também será criado o cronograma de  projeto e busca dos recursos necessários, tanto de custos quanto os humanos. É hora de detalhar todos os processos: escopo, tempo, custos, qualidade, recursos humanos, plano de gerenciamento de comunicação, riscos, aquisições e stakeholders (pessoas interessadas no projeto).</p>

<p align = "justify">Finalmente, pode-se dar início à elaboração do plano de projeto. Após isso, é realizada a reunião de kick off, quando  tudo o que foi definido e planejado vai ser exposto para um time muito maior, que será interessado e envolvido neste trabalho.</p>

## Desenvolvimento de uma Estrutura Análitica do Projeto (EAP)

<p align = "justify">É uma ferramenta que organiza todo o escopo do projeto de maneira visual, subdividindo o mesmo em entregas de maneira que essas sejam melhores gerenciadas. Ao invés do gerente de projetos apresentar um documento textual extenso às partes interessadas (patrocinador, clientes, equipe, gerente funcional, gerente de portfólio e pessoas afetadas pelo projeto), ele apresenta a EAP, fornecendo uma visão rápida e geral do que está incluso no escopo do projeto, facilitando a análise e ajudando a identificar possíveis incoerências e necessidades. Também ajuda o gerente de projetos e a equipe de desenvolvimento a não se esquecerem dos elementos solicitados, evitando impactos negativos e diminuindo o número de solicitações de mudanças.</p>

Para criar uma EAP, são **necessárias** as seguintes entradas:

1. Plano de gerenciamento do projeto;
2. Declaração do escopo do projeto;
3. Documentação dos requisitos;
4. Fatores ambientais da empresa;
5. Ativos de processos organizacionais.

Podem ser utilizadas as seguintes **ferramentas**:

1. Decomposição
2. Opinião especializada.

E irá resultar nas seguintes **saídas**:

1. Linha de base do escopo;
2. Atualizações dos documentos do projeto.

Algumas **regras** a serem seguidas para o desenvolvimento de uma EAP:

* A EAP deve ser criada com a ajuda da equipe;
* Cada nível da EAP é uma parte menor do nível anterior;
* O projeto inteiro deve ser incluso em cada um dos níveis mais elevados da EAP;
* A EAP deve incluir apenas as entregas necessárias para o projeto;
* As entregas que não estão na EAP não fazem parte do projeto.

Os níveis da EAP podem ser numerados para facilitar a rastreabilidade dos pacotes de trabalho. Não há regras para o tipo de numeração. Segue um exemplo de **EAP** abaixo:

![Exemplo de EAP](https://i1.wp.com/blogdaqualidade.com.br/app/uploads/2015/05/gerenciamento-escopo-do-projeto.png?resize=610%2C376&ssl=1)


## Referências

[Fases de um Projeto: Saiba tudo sobre as etapas imprescindíveis](https://robsoncamargo.com.br/blog/Fases-de-um-projeto-saiba-tudo-sobre-as-etapas-imprescindiveis)

[Gerenciamento de Escopo: Estrutura Analítica de Projetos (EAP)](https://blogdaqualidade.com.br/o-gerenciamento-de-escopo-estrutura-analitica-de-projetos-eap/)

**Comment by matheusgvieira** [comment]
# Comentário sobre Atividade
<p>Durante a última reunião foi levantado o problema sobre a execução da atividade, pois ela depende do andamento do projeto, ou seja, informações mais detalhadas que ainda não foram definidas são necessárias para seja bem executada. Tendo em vista as orientações do gerente, foi realizado uma EAP mais geral, abrangendo o projeto como um todo. O seguinte documento está abaixo:  </p>

[EAP - PI1.pdf](https://github.com/fga-projeto-integrador-1/Projeto/files/3101971/EAP.-.PI1.pdf)

**Comment by rogerioo** [comment]
Primeira versão concluída com sucesso!
