### ISSUE TITLE
Pesquisa de materiais alternativos para viga

### ISSUE THREAD

**Issue by rogerioo** [fga-projeto-integrador-1/Projeto#53]
Pesquisar substitutos viáveis ao compensado como material de construção da viga, visando reduzir suas dimensões finais.
(Cálculos disponíveis em:
 https://docs.google.com/spreadsheets/d/16MdHGEufKPm99tJczEV1tLqlbVWdI2Rc8nQqf3qWxlI/edit?usp=sharing )

### Critérios de aceitação:

- [x]  Encontrar um material que atenda os requisitos;
- [x] Atentar-se a possíveis mudanças de geometria com materiais alternativos.

**Comment by MonteiroC** [comment]
Como já falado anteriormente, nossa melhor opção até o momento do material que será utilizado para o nosso projeto é o MDF. Vi alguns tipos de materiais diferentes, como o alumínio e o aço, porém por questões de custos, fica praticamente inviável para o nosso projeto. 
 Ainda estou pesquisando se à possibilidade de troca do material, mas nada muito satisfatório até o momento.

**Comment by rogerioo** [comment]
Tudo certo @MonteiroC, os meninos já fecharam os dimensionamentos da viga usando o MDF e os valores estão satisfatórios! Podemos dar essa issue como encerrada, obrigado!

**Comment by DaniloFernandesDuarte** [comment]
Fixado chapas de Poliestireno pros cálculos.
Módulo de elasticidade próximo do acrílico e já vamos estar comprando um bocado para a difusão da iluminação da caixa
