### ISSUE TITLE
Criação da primeira versão do microsserviço CalculusAPI

### ISSUE THREAD

**Issue by rogerioo** [fga-projeto-integrador-1/Projeto#54]
## Descrição da Issue
Iniciar o desenvolvimento da API que irá receber os parâmetros que descrevem váriaveis como tipo dos apoios, cargas e posicionamento dos mesmos na viga e gera com isso os diagramas de MecSol, utilizando a biblioteca anaStruct.

### Critérios de aceitação.

- [x] API conseguindo receber os parâmetros via requisição HTTP.
- [x] API conseguindo gerar as imagens dos diagramas.

**Comment by MarcosNBJ** [comment]
Pull request cumprindo o pedido pela issue realizado no repositório do microsserviço [ssol-calculus-api](https://github.com/ssol-organization/SSol-Calculus-API) . Incluindo documentação exemplificando o funcionamento através do [readme](https://github.com/ssol-organization/SSol-Calculus-API/blob/feature/generate-diagram/README.md)

**Comment by rogerioo** [comment]
Foi realizado a revisão do código e tá tudo certinho! Código muito bem explicado e legível Já está disponível na branch develo do repositório do microsserviço [ssol-calculus-api](https://github.com/ssol-organization/SSol-Calculus-API).
