### ISSUE TITLE
Colocar ambiente do Image Process API em produção

### ISSUE THREAD

**Issue by rogerioo** [fga-projeto-integrador-1/Projeto#56]
## Descrição da Issue
Colocar em ambiente de produção o microsserviço de processamento de imagem.

### Critérios de aceitação.

- [ ] Endpoints da API acessiveis por um endereço na web.
- [ ] Ambiente de produção configurado para deploy continuo das versões estáveis da API

**Comment by MarcosNBJ** [comment]
Issue ainda em progresso, pois precisarão ser feitas algumas mudanças extras para a utilização do OpenCV no Heroku

**Comment by MarcosNBJ** [comment]
Issue concluida com sucesso, URL do ambiente em produção: https://ssolimprocessingapi.herokuapp.com/
