### ISSUE TITLE
Colocar ambiente do Calculus API em produção

### ISSUE THREAD

**Issue by rogerioo** [fga-projeto-integrador-1/Projeto#57]
## Descrição da Issue
Colocar em ambiente de produção o microsserviço de geração dos diagramas, Calculus API.

### Critérios de aceitação.

- [x] Endpoints da API acessiveis por um endereço na web.
- [x] Ambiente de produção configurado para deploy continuo das versões estáveis da API

**Comment by MarcosNBJ** [comment]
Issue realizada e API acessível através da URL https://calculusapi.herokuapp.com/get_diagram?tipo=0 . O deploy foi configurado para ser feito automaticamente através da branch master, como anteriormente definido na política de branches.
