### ISSUE TITLE
Confecção do CAD da Câmera

### ISSUE THREAD

**Issue by rogerioo** [fga-projeto-integrador-1/Projeto#61]
# Descrição da Issue
Criar CAD da câmera. 

## Tasks:
- [x] Arquivo com o CAD.
- [x] Relatório de Atividade.

## Critérios de Aceitação:
- Documentação.
- No mínimo dois comentários da issue.

# Assignees
@matheusgvieira

**Comment by matheusgvieira** [comment]
## Arquivos do CAD

[CAD.zip](https://github.com/ssol-organization/Wiki/files/3225625/CAD.zip)

**Comment by matheusgvieira** [comment]
### Relatório de Atividade
[Modelo de Relatório de Atividade.docx.pdf](https://github.com/ssol-organization/Wiki/files/3225650/Modelo.de.Relatorio.de.Atividade.docx.pdf)
