### ISSUE TITLE
Definição do suporte da câmera

### ISSUE THREAD

**Issue by rogerioo** [fga-projeto-integrador-1/Projeto#63]
# Descrição da Issue
Fazer pesquisa para definição do suporte da câmera. É preciso ter cuidado com o tamanho e a posição da câmera.  

## Tasks:
- [x] Pesquisa do Suporte da Câmera
- [x] Relatório de Atividade

## Critérios de Aceitação:
- Documentação.
- No mínimo dois comentários da issue.

# Assignees
@haackmarcella

**Comment by matheusgvieira** [comment]
## Pesquisa sobre o suporte da Câmera
[Pesquisa - suporte para camera.docx.pdf](https://github.com/ssol-organization/Wiki/files/3221752/Pesquisa.-.suporte.para.camera.docx.pdf)

**Comment by haackmarcella** [comment]
[Relatório de atividades -  Definição do suporte da câmera .pdf](https://github.com/ssol-organization/Wiki/files/3225222/Relatorio.de.atividades.-.Definicao.do.suporte.da.camera.pdf)
