### ISSUE TITLE
Testes de iluminação simulando a bancada

### ISSUE THREAD

**Issue by rogerioo** [fga-projeto-integrador-1/Projeto#64]
# Descrição da Issue
 Testes de iluminação com fitas de led. 

## Tasks:
- [x] Comentar issue com imagens após teste.
- [x] Relatório de Atividade.

## Critérios de Aceitação:
- Documentação.
- No mínimo dois comentários da issue.

# Assignees
@haackmarcella 
@Vkaio

**Comment by Vkaio** [comment]
[Relatório de Atividade - Simulação LEDs.pdf](https://github.com/ssol-organization/Wiki/files/3230629/Relatorio.de.Atividade.-.Simulacao.LEDs.pdf)

**Comment by Vkaio** [comment]
![i](https://user-images.githubusercontent.com/28969347/58527324-89ecd800-81a8-11e9-97cc-5a92e25a9e40.jpg)
