### ISSUE TITLE
Ler Documentação do PC1 para Provável Avaliação

### ISSUE THREAD

**Issue by rogerioo** [fga-projeto-integrador-1/Projeto#8]
## Descrição da Issue
Como acordado na última daily, todo os membros devem ler o documento de viabilidade técnica para poder estar iterado sobre tudo relacionado ao projeto.

### Tasks:
- [x] Ler [documento](https://drive.google.com/open?id=1jqauqhYCoeA4TehHNRD49vpWm_9TSDj3)
- [x] Comentar na issue possíveis dúvidas ou ciência

## Assignees
@amandahenriques 
@rogerioo 
@MarcosNBJ 
@Vkaio 
@DanilloGS 
@joao15victor08 
@matalencar 
@matheusgvieira 
@MonteiroC 
@haackmarcella 
@DaniloFernandesDuarte 
@jaosvgarcia 
@iaraandrade 
@pedroeagle 
@GabrielDVpereira 
@LucasGlopes

**Comment by matheusgvieira** [comment]
Nós vamos usar o ftool ou fazer um aplicativo?

**Comment by pedroeagle** [comment]
> Nós vamos usar o ftool ou fazer um aplicativo?

vamos fazer um aplicativo que gera um ftl e utilizar o ftool com esse arquivo

**Comment by MarcosNBJ** [comment]
> > Nós vamos usar o ftool ou fazer um aplicativo?
> 
> vamos fazer um aplicativo que gera um ftl e utilizar o ftool com esse arquivo

Na realidade não usaremos mais o Ftool, faremos uma aplicação que irá usar a biblioteca Python [anaStruc](https://github.com/ritchie46/anaStruct) para gerar os diagramas e afins.

**Comment by rogerioo** [comment]
Issue concluída com Hangout realizado pelo grupo no dia 02/05 ás 21 hrs.
