### ISSUE TITLE
Definir os materiais à serem utilizados

### ISSUE THREAD

**Issue by rogerioo** [fga-projeto-integrador-1/Projeto#9]
Definir os materiais à serem utilizados para a bancada

**Comment by DaniloFernandesDuarte** [comment]
Definimos os materiais principais da bancada, e por consequência assumimos que também a maior parte dos custos.

**Comment by rogerioo** [comment]
Por certas dificuldades encontradas pelo grupo e por ser uma fase essêncial do projeto, ele foi alocada para a sprint 03 e está sendo atendida por essa [issue](#36).
